### ISSUE TITLE
Dreambooth with custom CKPT -- Error no file named model_index.json

### ISSUE THREAD

**Issue by ChrGriffin** [replicate/dreambooth#29]
When attempting to use the Dreambooth API to train some custom CKPT files, the job will fail and this error will be logged.

`OSError: Error no file named model_index.json found in directory cog_custom_base_data.`

In my case, this occurred with the following model: https://civitai.com/models/4384/dreamshaper
That model provides multiple .ckpt files, I was using `dreamshaper_331BakedVae.ckpt`.
The prediction job ID is `jkghijcnbbavznmgkc3pi4fcty`.

Another user experienced the same bug with https://civitai.com/models/4201/realistic-vision-v13. (see Discord: https://discord.com/channels/775512803439280149/1074390955639177336)

For the sake of completeness, my payload generation is below (in PHP, but I'm sure you can get the gist).

```
$response = $client->post('/v1/predictions', [
    RequestOptions::JSON => [
        'version' => '9c41656f8ae2e3d2af4c1b46913d7467cd891f2c1c5f3d97f1142e876e63ed7a',
        'input' => [
            'instance_prompt' => Str::replace('_', ' ', $name),
            'class_prompt' => $gender,
            'instance_data' => 'https://an_s3_url',
            'num_class_images' => 200,
            'save_sample_prompt' => 'a photo of ' . Str::replace('_', ' ', $name),
            'resolution' => 512,
            'max_train_steps' => 1500,
            'ckpt_base' => 'https://a_long_s3_presigned_url'
        ],
    ],
]);
```

**Comment by ChrGriffin** [comment]
Quick update: I think the underlying error is the state_dict missing some keys. At the top of the stack trace, I can see this error:

```
Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias".
Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight".
```

**Comment by KevinGutowski** [comment]
I'm running into the exact same issue.

**Comment by Pwntus** [comment]
Hi folks, we fixed an issue with the **Dreambooth trainer that trains on top of an existing custom CKPT**, which improves compatibility with many CKPT files that failed previously. The new trainer version is `a8ba568da0313951a6b311b43b1ea3bf9f2ef7b9fd97ed94cebd7ffd2da66654`. You can also find it under the "versions" tab here: https://replicate.com/replicate/dreambooth/versions

**Comment by andygphillips** [comment]
Hi @Pwntus, I'm using the latest trainer version `a8ba568da0313951a6b311b43b1ea3bf9f2ef7b9fd97ed94cebd7ffd2da66654 ` but still seeing the "model_index.json" error for almost every huggingface checkpoint file I try, including:

- https://huggingface.co/wavymulder/portraitplus/blob/main/portrait%2B1.0.ckpt
- https://huggingface.co/SG161222/Realistic_Vision_V1.4/blob/main/Realistic_Vision_V1.4.ckpt
- https://huggingface.co/SG161222/Realistic_Vision_V2.0/blob/main/Realistic_Vision_V2.0-fp16-no-ema-inpainting.ckpt

This one works:

- https://huggingface.co/dreamlike-art/dreamlike-photoreal-2.0/resolve/main/dreamlike-photoreal-2.0.ckpt
